# Generated by Django 4.2.3 on 2023-09-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='formal_title',
            field=models.CharField(max_length=4),
        ),
    ]
