# Generated by Django 4.2.3 on 2023-09-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='afiliation',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
