# Generated by Django 4.2.3 on 2023-09-19 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_user_afiliation_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferenceTitle', models.CharField(max_length=255, unique=True)),
                ('about_conference', models.TextField()),
                ('organizing_institute', models.CharField(max_length=255)),
                ('institute_details', models.TextField()),
                ('submission_deadline', models.DateField()),
                ('notification_of_acceptance', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('camera_ready_papers', models.DateField()),
                ('conference_date', models.DateField()),
                ('conference_venue', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizingCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('conferenceTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.conference')),
            ],
            options={
                'unique_together': {('conferenceTitle', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdvisoryCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('conferenceTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.conference')),
            ],
            options={
                'unique_together': {('conferenceTitle', 'name')},
            },
        ),
    ]
