# Generated by Django 4.2.3 on 2023-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0005_user_afiliation_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='afiliation',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default=None, max_length=225, null=True),
        ),
    ]
