# Generated by Django 4.2.3 on 2023-09-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0007_author_paper_track_reviewer_paper_track_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizingcommittee',
            name='role_insititute',
            field=models.TextField(null=True),
        ),
    ]
