# Generated by Django 4.2.3 on 2023-09-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0008_organizingcommittee_role_insititute'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorycommittee',
            name='insititute',
            field=models.TextField(null=True),
        ),
    ]
