# Generated by Django 4.2.3 on 2023-09-28 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0010_alter_organizingcommittee_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='programChair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
