# Generated by Django 4.2.3 on 2023-09-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0013_conferenceimages_committeeimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeeimages',
            old_name='committee_images',
            new_name='committee_image',
        ),
        migrations.RenameField(
            model_name='conferenceimages',
            old_name='conference_images',
            new_name='conference_image',
        ),
    ]
