# Generated by Django 4.2.3 on 2023-09-29 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0016_alter_track_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='about_conference',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_venue',
            field=models.CharField(max_length=225, null='True'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='institute_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='programChair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
