# Generated by Django 4.2.3 on 2023-10-15 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0019_paper_otherauthors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='title',
            new_name='papertitle',
        ),
    ]
