# Generated by Django 4.2.3 on 2023-10-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0020_rename_title_paper_papertitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.author'),
        ),
    ]
