# Generated by Django 4.2.3 on 2023-10-16 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0022_alter_paper_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='papers',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CMS.conference'),
        ),
    ]
