# Generated by Django 4.2.3 on 2023-10-16 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0023_remove_reviewer_papers_reviewer_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='conference',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='CMS.conference'),
        ),
    ]
