# Generated by Django 4.2.3 on 2023-10-29 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0026_alter_review_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='originality',
        ),
        migrations.AddField(
            model_name='review',
            name='confidentialremarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='modeOfPreapartion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
