# Generated by Django 4.2.3 on 2023-11-01 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0027_remove_review_originality_review_confidentialremarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='modeOfPreapartion',
            new_name='modeOfPreparation',
        ),
    ]
