# Generated by Django 4.2.3 on 2024-01-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0028_rename_modeofpreapartion_review_modeofpreparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='registered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
