# Generated by Django 4.2.3 on 2024-01-20 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0029_author_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='registered',
        ),
        migrations.CreateModel(
            name='registered_authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMS.author')),
            ],
        ),
    ]
