# Generated by Django 4.2.3 on 2024-01-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0030_remove_author_registered_registered_authors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_authors',
            old_name='user',
            new_name='author',
        ),
    ]
