# Generated by Django 4.2.10 on 2024-03-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0031_rename_user_registered_authors_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='paper',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='papers', to='CMS.reviewer'),
        ),
    ]
