# Generated by Django 4.2.10 on 2024-03-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0032_remove_paper_reviewer_paper_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('Desktop Rejected', 'Desktop Rejected')], default='submitted', max_length=20),
        ),
    ]
