# Generated by Django 4.2.10 on 2024-03-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0033_alter_paper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('Rejected due to Plagarism', 'Rejected due to Plagarism'), ('Desktop Rejected', 'Desktop Rejected')], default='submitted', max_length=50),
        ),
    ]
