# Generated by Django 4.2.4 on 2024-05-09 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0006_alter_user_afiliation_alter_user_role'),
        ('CMS', '0034_alter_paper_status'),
    ]

    operations = [
    ]
