# Generated by Django 4.2.4 on 2024-08-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0035_merge_20240509_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeimages',
            name='committee_image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='conferenceimages',
            name='conference_image',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='file',
            field=models.FileField(upload_to='paper/'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='otherauthors',
            field=models.TextField(blank=True, null=True),
        ),
    ]
