# Generated by Django 4.2.4 on 2025-02-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0036_alter_committeeimages_committee_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_authors',
            name='paper',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='CMS.paper'),
        ),
    ]
